---
ID: "592fb462-926e-4679-a372-6236f13e11ef"
Parent: "3d7252a0-16ac-47c1-a954-3c35b3960b63"
Template: "3d7252a0-16ac-47c1-a954-3c35b3960b63"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Pipeline Steps/Get Labels Pipeline Step/__Standard Values
DB: master
SharedFields:
- ID: "3c7f78cc-0c5c-4076-80ef-9a49fda5ff96"
  Hint: ConverterType
  Value: Brightcove.DataExchangeFramework.Converters.PipelineStepWithEndpointFromConverter, Brightcove.DataExchangeFramework
- ID: "a83a2eb2-bfa1-4d3f-9f17-0cc6c9a91c42"
  Hint: ProcessorType
  Value: Brightcove.DataExchangeFramework.Processors.GetLabelsPipelineStepProcessor, Brightcove.DataExchangeFramework
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210917T001556Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
