---
ID: "7d78d8eb-1dfd-4a9e-9da7-9909bc5c58fc"
Parent: "8b6a9ead-4de9-4c59-b8f5-f3ff40a64f12"
Template: "8b6a9ead-4de9-4c59-b8f5-f3ff40a64f12"
Path: /sitecore/templates/Brightcove/Brightcove Video Label/__Standard Values
DB: master
SharedFields:
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Type: checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220822T180449Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
