---
ID: "601b2caa-864b-4b43-a990-ff619cc2b736"
Parent: "2aacdf56-8d6e-4e38-9e84-690561575946"
Template: "2aacdf56-8d6e-4e38-9e84-690561575946"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Pipeline Steps/Resolve Folder Model Pipeline Step/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Applications/16x16/document.png
- ID: "3c7f78cc-0c5c-4076-80ef-9a49fda5ff96"
  Hint: ConverterType
  Value: Brightcove.DataExchangeFramework.Converters.ResolveOrUpdateAssetModelPipelineStepConverter, Brightcove.DataExchangeFramework
- ID: "a83a2eb2-bfa1-4d3f-9f17-0cc6c9a91c42"
  Hint: ProcessorType
  Value: Brightcove.DataExchangeFramework.Processors.ResolveFolderModelPipelineStepProcessor, Brightcove.DataExchangeFramework
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T205319Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
