---
ID: "c60adc3d-4aa2-4ca5-b792-5e734159421d"
Parent: "5b822f3f-d51a-48c8-88a8-ff38f8799f2c"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Pipeline Steps/Resolve Label Model Pipeline Step/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T203951Z
