---
ID: "5389dd90-1739-4faa-87fa-c2b2e4cde095"
Parent: "608ad9e5-51a1-4673-a454-2cc7c2be2a6c"
Template: "b2613cc1-a748-46a3-a0db-3774574bd339"
Path: /sitecore/templates/Branches/Data Exchange/Providers/Brightcove/Commands/Brightcove Tenant Settings
DB: master
BranchID: "d1dcfbcc-dacc-414f-bdc4-8a3e1c41988b"
SharedFields:
- ID: "854cc8f6-94ad-4521-a4b6-44ed8f794c98"
  Hint: Command
  Value: "dataExchange:createItemWithoutPromptingForNameCommand(settingsItem={5389DD90-1739-4FAA-87FA-C2B2E4CDE095})"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 2000
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{BF1E390B-56CA-45AF-ACA0-58627A659C9D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T202004Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
