---
ID: "b5f5e102-7dd0-4c31-8d6a-1ff588af21b2"
Parent: "a7eaf4fd-bcf3-4511-9e8c-2ed0b165f1d6"
Template: "a7eaf4fd-bcf3-4511-9e8c-2ed0b165f1d6"
Path: /sitecore/templates/Brightcove/BrightcoveVideoVariant/__Standard Values
DB: master
SharedFields:
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
- ID: "c0e276bb-8807-40aa-8138-e5c38b0c5dab"
  Hint: __Quick Actions
  Type: Multilist
  Value: 
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090813T110100Z
    - ID: "2bf865a0-e595-4e8c-926f-dc1f9060a189"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
