---
ID: "4821ef79-7ed7-4270-a626-0ece3ebd63be"
Parent: "b25b0b2d-9aef-4fcf-99b4-d802c8f6fd20"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: /sitecore/templates/Branches/Data Exchange/Providers/Brightcove/Branches/Brightcove Tenant Settings Root
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T202003Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
