---
ID: "13d202d3-15d7-47c3-8ea5-230b94962edb"
Parent: "617228b5-978e-48c9-bed9-79826ef07142"
Template: "617228b5-978e-48c9-bed9-79826ef07142"
Path: /sitecore/templates/Brightcove/Brightcove Experience/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230419T160845Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
