---
ID: "e4b09a3a-c9c9-426d-93fa-45b763e73a06"
Parent: "a14043f1-a5e4-49dc-9813-f6191d800961"
Template: "b0c4da22-e26f-472a-9fe9-7a5030684a14"
Path: /sitecore/templates/Branches/Data Exchange/Framework/Branches/Brightcove Tenant/$name/Tenant Settings
DB: master
BranchID: "0d21226f-7b04-4ff2-9230-b55245cf6fe7"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E4B09A3A-C9C9-426D-93FA-45B763E73A06}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T212038Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
