---
ID: "ac220526-c26f-44a3-996c-2ea2f0932ce8"
Parent: "59cb8c44-3c39-4ab5-9b51-0900b14aaf4f"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Endpoints/Web API Endpoint/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211103T100056Z
